# Generated by Django 5.2.10 on 2026-01-29 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0002_initial"),
        ("trivias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="trivia",
            name="created_by",
            field=models.ForeignKey(
                help_text="The admin user who created this trivia.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trivias_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="trivia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="trivias.trivia",
                verbose_name="Trivia",
            ),
        ),
        migrations.AddField(
            model_name="triviaquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trivia_questions",
                to="questions.question",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="triviaquestion",
            name="trivia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trivia_questions",
                to="trivias.trivia",
                verbose_name="Trivia",
            ),
        ),
        migrations.AddField(
            model_name="trivia",
            name="questions",
            field=models.ManyToManyField(
                help_text="The set of questions included in this trivia.",
                related_name="trivias",
                through="trivias.TriviaQuestion",
                to="questions.question",
                verbose_name="Questions",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="chosen_choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="questions.choice",
                verbose_name="Chosen Choice",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="participation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="trivias.participation",
                verbose_name="Participation",
            ),
        ),
        migrations.AddField(
            model_name="useranswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_answers",
                to="questions.question",
                verbose_name="Question",
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["trivia", "total_score"], name="trivias_par_trivia__ab25f8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("user", "trivia")},
        ),
        migrations.AddIndex(
            model_name="triviaquestion",
            index=models.Index(
                fields=["trivia", "order"], name="trivias_tri_trivia__0acb1c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="triviaquestion",
            unique_together={("trivia", "question")},
        ),
        migrations.AddIndex(
            model_name="useranswer",
            index=models.Index(
                fields=["participation", "question"],
                name="trivias_use_partici_0d12ba_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together={("participation", "question")},
        ),
    ]
