# Generated by Django 5.2.10 on 2026-01-29 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trivias", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trivia",
            name="created_by",
        ),
    ]
