# Generated by Django 5.2.10 on 2026-01-29 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trivias", "0003_remove_trivia_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participation",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
        migrations.AlterField(
            model_name="participation",
            name="start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Start Time"
            ),
        ),
    ]
