# Generated by Django 5.2.10 on 2026-01-29 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                help_text="The admin user who created this question.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="questions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="question",
            field=models.ForeignKey(
                help_text="The question this choice belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="questions.question",
                verbose_name="Question",
            ),
        ),
        migrations.AddIndex(
            model_name="choice",
            index=models.Index(
                fields=["question"], name="questions_c_questio_2d835e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="choice",
            index=models.Index(
                fields=["is_correct"], name="questions_c_is_corr_4a0f07_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="choice",
            unique_together={("question", "text")},
        ),
    ]
