# Generated by Django 5.2.10 on 2026-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="choice",
            name="questions_c_questio_2d835e_idx",
        ),
        migrations.RemoveIndex(
            model_name="choice",
            name="questions_c_is_corr_4a0f07_idx",
        ),
        migrations.RemoveField(
            model_name="question",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="choice",
            name="is_correct",
            field=models.BooleanField(
                default=False,
                help_text="Marks if this choice is the correct answer.",
                verbose_name="Correct Answer",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("question", "text"), name="unique_choice_text_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_correct", True)),
                fields=("question",),
                name="unique_correct_choice_per_question",
            ),
        ),
    ]
